[project]
name = "midimaxxing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "av==14.1.0",
    "gdown>=6.1.0",
    "ipython>=9.15.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.0",
    "nvidia-dali-cuda120>=2.2.0",
    "ppan",
    "pretty-midi>=0.2.11",
    "pyfluidsynth>=1.4.0",
    "requests>=2.32.5",
    "scipy>=1.18.0",
    "timm>=1.0.27",
    "tqdm>=4.68.3",
    "ultralytics>=8.4.90",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.sources]
ppan = { workspace = true, editable = true }

[tool.uv.workspace]
members = [
    "vendor_ppan",
]
