# -*- coding: utf-8 -*-
"""Copy of Pay Attention to the Keys: Visual Piano Transcription Using Transformers-Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_FtPoygJWTMRlmKVGqOsrEWZnCTcI6P

# Pay Attention to the Keys: Visual Piano Transcription Using Transformers -  Performing Inference

This notebook demonstrates the steps required to perform inference on a video using our best model (presented in Section 3).

## Instructions for Use:
Because we use specific versions of certain libraries (such as NumPy and SciPy) and also require libraries that do not come pre-installed in the default Colab environment (such as ```fluidsynth``` or ```pretty_midi```), the relevent packages need to be installed before running the rest of the notebook.
The steps are as follows:

1. Run the first code cell and wait for it to complete (this can take several minutes). Messages about the runtime crashing can be ignored, this is intended behaviour to guarantee newly installed packages are loaded.
2. Rerun all cells (including the first) as usual.

When running the notebook make sure to use an instance with a connected GPU (e.g. T4).

## Notebook Outline

This notebook performs inference on an example video from R3s, taking the following steps:

1. Loading the video as a sample for use with the model
3. Getting predictions from the model as described in Section 3
4. Visualizing the actual model inputs as described in Section 5.1
4. Comparing generated pianorolls using either onsets and frames or only frames
5. Generating a MIDI and audio file
"""



"""## Initial Setup

This step can take a while because we download not only what we need for running the model, but also the tools we need to load video files and work with MIDI files.
We also download the video on which we perform inference as well as all model weights.

**This cell must be run twice, once to install all required packages and once to import all installed packages.**
"""

import os
from pathlib import Path
from typing import Optional
import glob
import sys

from IPython.display import Audio, clear_output

import subprocess

try:
    import pretty_midi
    from scipy import io
    import matplotlib
    matplotlib.use('Agg')
    from matplotlib import animation
    from matplotlib import rc
    import matplotlib.pyplot as plt
    import numpy as np
    import numpy.typing as npt
    import torch
    from torch import no_grad, squeeze
    import torchvision
    from torchvision.utils import draw_bounding_boxes
    from torchvision.transforms import v2
    from ppan.utils import Sample
    from ppan.model import PPANModel, PPANVideoProcessor
    from ppan.preprocessor import DatasetProcessor
    from ppan.evaluate import evaluate_on_dataset
    from tqdm import tqdm
    from timm.data.constants import IMAGENET_DEFAULT_STD, IMAGENET_DEFAULT_MEAN

except ImportError as f:
    raise RuntimeError(
        "Missing dependencies. Run: uv sync && uv add nvidia-dali-cuda120 "
        "\"ppan @ git+https://github.com/Chromeilion/ppan@minimal-eval\""
    ) from f

# Useful for typing
PathLike = str | os.PathLike

"""## Parameters
These parameters can be used to modify how this notebook runs.
We encourage you to experiment with different threshold and smoothing values to see the impact on the final output.

Although we provide a demo video, if you'd like to use your own video/s, make sure that they are all the same frame-rate of 30.
They should also all be in a format supported by the [Nvidia DALI](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/index.html) library.
If the piano player is at the bottom of the image with the paino above them, make sure to set rotate_180 to True.
Any custom video should also have a corresponding crop.
These parameters can all be set in the ```video_files``` and ```bounding_boxes``` lists below.

"""

# Dataset settings
## Whether to rotate the video 180 degrees, not needed for samples from R3
rotate_180: Optional[bool] = False

# Output settings
## Directories to output generated MIDI and WAV files to.
wav_output_dir: PathLike = "./preds_wav"

# Model settings
model_checkpoint: PathLike = "./weights"
batch_size: int = 32

# Settings for model output post-processing
threshold_onset: float = 0.5
threshold_frame: float = 0.5
gaussian_sigma_onsets: float = 0.2
gaussian_sigma_frames: float = 0.8

# The files we would like to process with their bounding boxes.
# Usage:
#   python vit.py                          → demo video with hardcoded crop
#   python vit.py video.mp4               → interactive crop picker
#   python vit.py video.mp4 x1,y1,x2,y2  → use provided crop directly

_DEMO_BB = {"rot_angle": 0, "x1": 519, "y1": 631, "x2": 1373, "y2": 722}

_PICKER_SCRIPT = '''
import sys, json
import av
import numpy as np
import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt

path = sys.argv[1]
container = av.open(path)
vs = container.streams.video[0]
container.seek(vs.duration // 2, stream=vs)
frame = next(container.decode(video=0))
img = frame.to_ndarray(format="rgb24")

fig, ax = plt.subplots(figsize=(14, 8))
ax.imshow(img)
ax.set_title(f"Click TOP-LEFT then BOTTOM-RIGHT of the piano keys  ({img.shape[1]}x{img.shape[0]})")
plt.tight_layout()
pts = plt.ginput(2, timeout=-1)
plt.close("all")
x1 = int(min(pts[0][0], pts[1][0]))
y1 = int(min(pts[0][1], pts[1][1]))
x2 = int(max(pts[0][0], pts[1][0]))
y2 = int(max(pts[0][1], pts[1][1]))
print(json.dumps({"x1": x1, "y1": y1, "x2": x2, "y2": y2}))
'''

def _pick_bbox_interactive(video_path: str) -> dict:
    import json
    result = subprocess.run(
        [sys.executable, "-c", _PICKER_SCRIPT, video_path],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    if result.returncode != 0:
        raise RuntimeError(f"Picker failed:\n{result.stderr.decode()}")
    coords = json.loads(result.stdout.decode().strip().split("\n")[-1])
    print(f"Bounding box: x1={coords['x1']}, y1={coords['y1']}, x2={coords['x2']}, y2={coords['y2']}")
    return {"rot_angle": 0, **coords}

_args = sys.argv[1:]
if not _args:
    video_files = ["./videos/ex1.mp4"]
    bounding_boxes = [_DEMO_BB]
elif len(_args) == 1:
    video_files = [_args[0]]
    bounding_boxes = [_pick_bbox_interactive(_args[0])]
else:
    video_files = [_args[0]]
    x1, y1, x2, y2 = map(int, _args[1].split(","))
    bounding_boxes = [{"rot_angle": 0, "x1": x1, "y1": y1, "x2": x2, "y2": y2}]

# Commented out IPython magic to ensure Python compatibility.
# If the MIDI and wav output directories don't exist we create them:
wav_output_dir = Path(wav_output_dir)
wav_output_dir.mkdir(exist_ok=True)

# For plotting animations.
# %matplotlib inline
rc('animation', html='jshtml')

def show(imgs):
    """
    Helper function for plotting tensors.
    """
    if not isinstance(imgs, list):
        imgs = [imgs]
    fig, axs = plt.subplots(ncols=len(imgs), squeeze=False,
                            figsize=(len(imgs)*5, 6))
    for i, img in enumerate(imgs):
        img = img.detach()
        img = v2.functional.to_pil_image(img)
        axs[0, i].imshow(np.asarray(img))
        axs[0, i].set(xticklabels=[], yticklabels=[], xticks=[], yticks=[])

"""## Data Loading

Here we combine video and other metadata into a unified Sample object which is much easier to work with.
"""

def prepare_data(videos: PathLike, bounding_boxes: bool):
    """
    Simple sample loading script. Feel free to modify this for your
    needs.

    Parameters
    ----------
    videos : list[PathLike]
    bounding_boxes : list[dict[str, int]]

    Returns
    -------
    samples : Sample
    """
    # Get all videos in the directory
    samples = []
    for vid, b in zip(videos, bounding_boxes):
        bounding_box_tup = (
            b["y1"], b["y2"], b["x1"], b["x2"]
        )
        samples.append(Sample(
            video_path=os.path.abspath(vid),
            bounding_box=bounding_box_tup,
            rotation_factor=b["rot_angle"],
            dataset="r3s",
            rotate_180=rotate_180
        ))
    return samples

samples = prepare_data(video_files, bounding_boxes)

"""It is informative to see what the bounding boxes look like."""

def visualize_bbs(samples, output_path="bounding_boxes.png"):
    """Visualize bounding boxes on up to 4 videos."""
    import av
    no_plots = min(len(samples), 4)
    results = []
    for sample in samples[:no_plots]:
        print(sample.video_path)
        container = av.open(sample.video_path)
        video_stream = container.streams.video[0]
        duration = float(video_stream.duration * video_stream.time_base)
        container.seek(int(duration / 2 / float(video_stream.time_base)))
        frame = next(container.decode(video=0))
        img = torch.from_numpy(frame.to_ndarray(format="rgb24")).permute(2, 0, 1)
        bb = sample.bounding_box
        bb = torch.tensor([[bb[2], bb[0], bb[3], bb[1]]], dtype=torch.float32)
        results.append(draw_bounding_boxes(img, boxes=bb, width=4, colors="red"))
    show(results)
    plt.savefig(output_path, bbox_inches="tight")
    print(f"Saved to {output_path}")

# Let's also visualize the bounding boxes:
visualize_bbs(samples=samples)

"""## Inference

With the samples loaded, we can now perform inference using the
trained model.
For this we utilize a helper function we have provided.
Inference is performed exactly as described in Section 3.
We generate pianorolls for both onsets and frames, as well as only frames.
Because the model always predicts both onsets and frames during the forward pass, we only need to generate one set of predictions to get all the data we need.
"""

dataset_name = Path(video_files[0]).stem

pianoroll_onf, ds_sample = evaluate_on_dataset(
    samples=samples,
    dataset_name=dataset_name,
    model_checkpoint=model_checkpoint,
    greyscale=True,
    batch_size=6,
    gaussian_sigma=gaussian_sigma_onsets,
    gaussian_sigma_frames=gaussian_sigma_frames,
    threshold_frame=threshold_frame,
    threshold_onset=threshold_onset,
    frame_only=False
)
pianoroll_frames_only, _ = evaluate_on_dataset(
    samples=samples,
    dataset_name=dataset_name,
    model_checkpoint=model_checkpoint,
    greyscale=True,
    batch_size=6,
    gaussian_sigma=gaussian_sigma_onsets,
    gaussian_sigma_frames=gaussian_sigma_frames,
    threshold_frame=threshold_frame,
    threshold_onset=threshold_onset,
    frame_only=True
)

"""### Visualizing model inputs
We take the opportunity to visualize exactly what the inputs to the model look like.
An extra figure is visualized below due to a bug in Colab.
"""

# The model accepts normalized inputs, however for visualization purposes we
# undo the normalization here.
unnormalizer = v2.Compose([
    v2.Normalize(
        mean=-torch.tensor(IMAGENET_DEFAULT_MEAN) / torch.tensor(IMAGENET_DEFAULT_STD),
        std=1 / torch.tensor(IMAGENET_DEFAULT_STD)
    ),
    v2.ToDtype(torch.uint8, scale=True)
])

# Get the first sample from the dataset.
# This corresponds to the start of the first video.
sample_frames = unnormalizer(ds_sample["pixel_values"][:, :6, ...]).cpu().numpy().squeeze()



# Print out the shape of the sample
sample_shape = sample_frames.shape
print(f"Our sample has a shape of {sample_shape} \n")

# Visualize the sample with an animation.
frames = []
fig, ax = plt.subplots()
for i in range(sample_frames.shape[0]):
    frame = np.transpose(np.squeeze(sample_frames[i, ...]), axes=(1, 2, 0))
    frames.append([ax.imshow(frame, animated=True)])

animation.ArtistAnimation(
    fig, frames, interval=33
)

"""## Visualizing Model Predictions

Here we visualize the predicted pianorolls.
They have already been smoothed and thresholded using the values defined above.
"""

n_timesteps = 400

fig, ax = plt.subplots(2, sharex=True, tight_layout=True)
ax[0].imshow(pianoroll_frames_only[:, :n_timesteps])
ax[0].set_title(" Only Frames")
ax[0].set_ylabel("Note Number")
ax[1].set_title(" Onsets and Frames")
ax[1].imshow(pianoroll_onf[:, :n_timesteps])
ax[1].set_ylabel("Note Number")
ax[1].set_xlabel("Time Step")
fig.suptitle("Pianoroll Predictions");

"""We can see that when using only frames there are more notes being predicted overall because we do not reject any notes like in the onsets and frames approach.
Many notes are also shorter when using both onsets and frames because the onset prediction can cause a note to start later than the frames may have predicted. The gaussian smoothing and thresholding process also behaves slightly differently between the two.

## Saving to MP3
Here we define a helper function that saves our predictions to a WAV file.
"""

def midi_to_wav(midi_file: Path,
                output_wav: Path) -> None:
    """
    Convert a MIDI file to a wav file.

    Parameters
    ----------
    midi_file : Path
    output_wav : Path
    """
    pm = pretty_midi.PrettyMIDI(str(midi_file))
    waveform = pm.fluidsynth(fs=44100)
    io.wavfile.write(output_wav, 44100, waveform)

"""## Generating Audio Files

With our helper functions we can iterate through our model predictions
and generate audio files.
"""

# Iterate through all videos and their predictions.
for midi_file in glob.glob("./midi/*.mid"):
    midi_to_wav(
        midi_file=midi_file,
        output_wav=wav_output_dir/(Path(midi_file).stem + ".wav")
    )

"""## Conclusion
With that we're done!
You can listen to a generated audio file below.
"""

# Pick an audio file from those in the audio file folder.
first_audio_file = str((wav_output_dir/os.listdir(wav_output_dir)[0]).absolute())

# We need to convert the WAV file to an MP3 so that it can be played in the
# browser.
subprocess.run(["ffmpeg", "-y", "-i", first_audio_file, "-vn", "-ar", "44100",
                "-ac", "2", "-b:a", "192k", "output.mp3"], check=False)
clear_output()

print("Done. Audio saved to output.mp3")

