[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ppan"
version = "0.1"
description = "Piano performance video analysis."
requires-python = ">=3.9"
authors = [
    {name = "Anonymous"}
]
dependencies = [
    "numpy",
    "mido",
    "tqdm",
    "scipy",
    "transformers[torch]<5.0",
    "matplotlib",
    "torchvision",
    "torch",
    "pillow",
    "timm",
    "partitura"
]

[tool.setuptools.packages.find]
include = ["ppan"]
